# 취소되지 않은 흉부외과(CS) 진료 예약 내역 조회
SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, APNT_YMD
FROM PATIENT P
JOIN (
    SELECT *
    FROM APPOINTMENT
    WHERE MCDP_CD = 'CS'
    AND DATE(APNT_YMD) = '2022-04-13'
    AND APNT_CNCL_YN = 'N'
) A
USING (PT_NO)
JOIN DOCTOR AS D
ON A.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD ASC